# Ch2.5 Linear Independence

## Concept Summary

**Linear Combination**
- a linear combination of vectors x1, ..., xk is any vector of the form λ1x1 + ... + λkxk where the scalars λi are real numbers

**Linear Independence**
- vectors are linearly independent if the only solution to λ1x1 + ... + λkxk = 0 is λ1 = ... = λk = 0. if a non-trivial solution exists, they are linearly dependent
- intuitively, a set of vectors is linearly dependent if at least one vector can be expressed as a linear combination of the others, meaning it carries no new information

**Checking Linear Independence**
- write the vectors as columns of a matrix and apply gaussian elimination. if every column has a pivot, the vectors are linearly independent. if any non-pivot column exists, the set is linearly dependent
- a non-pivot column is always a linear combination of the pivot columns to its left

**Special Cases**
- if any vector in the set is the zero vector, the set is linearly dependent
- if any vector is a scalar multiple of another, the set is linearly dependent
- if the number of vectors exceeds the dimension of the space, the set is always linearly dependent
- if m vectors are each expressed as linear combinations of k vectors and m > k, the m vectors are always linearly dependent


## Verification

**Example 2.14** gaussian elimination on three 4-dimensional vectors to confirm all columns have pivots, verifying linear independence.

**Example 2.15** gaussian elimination on four vectors to identify the non-pivot column, then reconstructing x4 as a linear combination of x1, x2, x3 to verify linear dependence explicitly.

**Remark: zero vector** any set containing the zero vector is linearly dependent. verified by checking rank against number of columns.

**Remark: scalar multiple** if one vector is a scalar multiple of another, the set is linearly dependent. verified by checking rank against number of columns.

**Remark: exceeding dimension** if the number of vectors exceeds the dimension of the space, the set is always linearly dependent. verified by checking rank against number of columns.


In [2]:
# Example 2.14: Gaussian elimination to determine linear independence

import numpy as np

x1 = np.array([1, 2, -3, 4], dtype=float)
x2 = np.array([1, 1,  0, 2], dtype=float)
x3 = np.array([-1,-2, 1, 1], dtype=float)

A = np.column_stack([x1, x2, x3])
print("Original Matrix:")
print(A)

def gauss_elimination(A):
    A = A.copy()
    rows, cols = A.shape
    pivot_cols = []

    row = 0
    for col in range(cols):
        # Find non-zero entry in current column (using 1e-10 for numerical stability)
        nonzero = np.where(np.abs(A[row:, col]) > 1e-10)[0]
        if len(nonzero) == 0:
            continue

        # Row swap
        pivot_row = nonzero[0] + row
        A[[row, pivot_row]] = A[[pivot_row, row]]

        # Row elimination to obtain Row Echelon Form (REF)
        for r in range(row+1, rows):
            factor = A[r, col] / A[row, col]
            A[r] -= factor * A[row]

        pivot_cols.append(col)
        row += 1
        if row == rows:
            break

    return A, pivot_cols

result, pivot_cols = gauss_elimination(A)

print("\nMatrix after Elimination (REF):")
print(np.round(result, 2))
print(f"\nPivot column indices: {pivot_cols}")
print(f"Number of pivots: {len(pivot_cols)}, Total columns: {A.shape[1]}")

# Final check for linear independence
if len(pivot_cols) == A.shape[1]:
    print("Every column contains a pivot -> Linearly Independent")
else:
    print("At least one column lacks a pivot -> Linearly Dependent")

Original Matrix:
[[ 1.  1. -1.]
 [ 2.  1. -2.]
 [-3.  0.  1.]
 [ 4.  2.  1.]]

Matrix after Elimination (REF):
[[ 1.  1. -1.]
 [ 0. -1.  0.]
 [ 0.  0. -2.]
 [ 0.  0.  0.]]

Pivot column indices: [0, 1, 2]
Number of pivots: 3, Total columns: 3
Every column contains a pivot -> Linearly Independent


In [ ]:
# Example 2.15 (Finding the dependent vector and verifying the linear dependence)
lam1 = np.array([ 1, -2,  1, -1], dtype=float)
lam2 = np.array([-4, -2,  0,  4], dtype=float)
lam3 = np.array([ 2,  3, -1, -3], dtype=float)
lam4 = np.array([17,-10, 11,  1], dtype=float)

A = np.column_stack([lam1, lam2, lam3, lam4])
result, pivot_cols = gauss_elimination(A)

print("After elimination")
print(np.round(result, 2))
print(f"\nPivot columns: {pivot_cols}")

# find non-pivot columns
all_cols = set(range(A.shape[1]))
non_pivot_cols = sorted(all_cols - set(pivot_cols))
print(f"Non-pivot columns: {non_pivot_cols}")  

# verify x4 = -7x1 - 15x2 - 18x3 (from textbook)
x4_reconstructed = -7*lam1 + (-15)*lam2 + (-18)*lam3
print(f"\nx4 original:     {lam4}")
print(f"x4 reconstructed: {x4_reconstructed}")
print(f"Verification: {np.allclose(lam4, x4_reconstructed)}") 

After elimination
[[  1.   -4.    2.   17. ]
 [  0.  -10.    7.   24. ]
 [  0.    0.   -0.2   3.6]
 [  0.    0.    0.   -0. ]]

Pivot columns: [0, 1, 2]
Non-pivot columns: [3]

x4 original:     [ 17. -10.  11.   1.]
x4 reconstructed: [ 17. -10.  11.   1.]
Verification: True


In [ ]:
# Any set containing the zero vector is always linearly dependent
x1 = np.array([1, 2])
x2 = np.array([0, 0])  # zero vector
x3 = np.array([3, 4])

A = np.column_stack([x1, x2, x3])
rank = np.linalg.matrix_rank(A)  # rank: number of linearly independent columns

print(f"Rank: {rank}")            
print(f"Number of columns: {A.shape[1]}")  

if rank == A.shape[1]:
    print("Linearly independent")
else:
    print("Linearly dependent")

Rank: 2
Number of columns: 3
Linearly dependent


In [6]:
# Two vectors that are scalar multiples are linearly dependent
x1 = np.array([1, 2, 3])
x2 = np.array([2, 4, 6])  

A = np.column_stack([x1, x2])
rank = np.linalg.matrix_rank(A)

print(f"Rank: {rank}")                    
print(f"Number of columns: {A.shape[1]}")

if rank == A.shape[1]:
    print("Linearly independent")
else:
    print("Linearly dependent")

Rank: 1
Number of columns: 2
Linearly dependent


In [7]:
# If the number of vectors exceeds the dimension, they are always linearly dependent
# 3 vectors in 2D space
x1 = np.array([1, 0])
x2 = np.array([0, 1])
x3 = np.array([3, 5])  # any third vector in 2D must be dependent

A = np.column_stack([x1, x2, x3])
rank = np.linalg.matrix_rank(A)

print(f"Rank: {rank}")                     # 2
print(f"Number of columns: {A.shape[1]}") # 3

if rank == A.shape[1]:
    print("Linearly independent")
else:
    print("Linearly dependent")

Rank: 2
Number of columns: 3
Linearly dependent


## Reflection Note

- stepping through gauss_elimination directly rather than calling matrix_rank made the structure visible. rank returns a number, but elimination shows which columns have pivots and which do not. in Example 2.15, that made it possible to go further: reconstructing x4 as -7x1 - 15x2 - 18x3 and verifying with np.allclose confirmed that dependence means one vector is literally built from the others.

- there are multiple ways to check linear independence: solving λ1x1 + ... = 0 directly, running gaussian elimination and counting pivots, or computing rank and comparing to the number of vectors. they all lead to the same answer but elimination makes the structure most explicit.

- the three remark cases (zero vector, scalar multiple, more vectors than dimensions) initially felt like separate rules, but they all reduce to the same condition: rank is less than the number of columns. different surface forms, same underlying criterion.