## Concept Summary

- A matrix is not just a grid of numbers, it represents a transformation applied to a vector
- Matrix addition: add element-wise, only possible when dimensions match
- Scalar multiplication: multiply every element by a single number
- Matrix multiplication: (A @ B) requires A's columns to equal B's rows, result is not element-wise
- AB ≠ BA in general, order matters
- Transpose: flip rows and columns, (AB)T = BT AT, order reverses
- Identity matrix: multiplying by I leaves any matrix unchanged, equivalent to 1 in scalar math
- Inverse matrix: AA⁻¹ = I, not all matrices have an inverse
- (AB)⁻¹ = B⁻¹A⁻¹, order reverses same as transpose
- Associative law: (AB)C = A(BC)
- Distributive law: A(B+C) = AB + AC

## Problems

1. A = [[1,2],[3,4]], B = [[5,0],[1,2]], A + B = [[6,2],[4,6]]
2. 3A = [[3,6],[9,12]]
3. AB = [[2,6],[0,3]], BA = [[2,4],[1,5]], AB ≠ BA confirmed
4. A = [[1,2,3]], B = [[1,2],[3,4]], AB impossible, A has 3 columns but B has 2 rows
5. A = [[1,2],[3,4]], AT = [[1,3],[2,4]]
6. A = [[2,1],[5,3]], A⁻¹ = [[3,-1],[-5,2]], verified AA⁻¹ = I
7. (AB)T = BT AT, not AT BT, because AB ≠ BA so reversing order is necessary for dimensions to hold
8. A = [[1,2],[3,4]], AI = IA = A, identity matrix leaves A unchanged
## Verification

In [ ]:
# prob 1 & 2
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 0],
              [1, 2]])

print("A + B =\n", A + B)
print("3A =\n", 3 * A)

A + B =
 [[6 2]
 [4 6]]
3A =
 [[ 3  6]
 [ 9 12]]


In [ ]:
# prob 3
# AB vs BA
A = np.array([[1, 2],
              [0, 1]])
B = np.array([[2, 0],
              [1, 3]])

print("AB =\n", A @ B)
print("BA =\n", B @ A)
print("AB == BA?", np.allclose(A @ B, B @ A))

AB =
 [[4 6]
 [1 3]]
BA =
 [[2 4]
 [1 5]]
AB == BA? False


In [ ]:
# prob 4
# Dimension mismatch
A = np.array([[1, 2, 3]])
B = np.array([[1, 2],
              [3, 4]])
try:
    print(A @ B)
except ValueError as e:
    print("Error:", e)

Error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)


In [ ]:
# prob 5
A = np.array([[1, 2],
              [3, 4]])

print("A =\n", A)
print("A transpose =\n", A.T)

A =
 [[1 2]
 [3 4]]
A transpose =
 [[1 3]
 [2 4]]


In [ ]:
# prob 6
A = np.array([[2, 1],
              [5, 3]])

A_inv = np.linalg.inv(A)
print("A inverse =\n", A_inv)
print("AA⁻¹ =\n", np.round(A @ A_inv))  # 단위행렬 나와야 함

A inverse =
 [[ 3. -1.]
 [-5.  2.]]
AA⁻¹ =
 [[ 1.  0.]
 [-0.  1.]]


In [10]:
# prob 7 
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[2, 0],
              [1, 3]])

print("(AB)T =\n", (A @ B).T)
print("BT AT =\n", B.T @ A.T)
print("equal?", np.allclose((A @ B).T, B.T @ A.T))

# prob 8
I = np.eye(2)
print("Identity matrix =\n", I)
print("AI =\n", A @ I) 

(AB)T =
 [[ 4 10]
 [ 6 12]]
BT AT =
 [[ 4 10]
 [ 6 12]]
equal? True
Identity matrix =
 [[1. 0.]
 [0. 1.]]
AI =
 [[1. 2.]
 [3. 4.]]


## Reflection Note
- Learned the structural difference between scalar multiplication and matrix multiplication. Scalar just scales every element, but matrix multiplication is built on dot products of rows and columns.
- AB requires A's columns to match B's rows. The constraint felt abstract until I tried a mismatched pair and got a dimension error, that made it click.
- Worked out AB and BA by hand and got different results. Knowing order matters theoretically is one thing, seeing the numbers diverge on paper made it stick.
- In Ch2.1, I noted a matrix can be read as a collection of column vectors. Ch2.2 made that more concrete, matrix multiplication is essentially applying a transformation column by column. Same object, clearer function.
- Transpose, inverse, and identity matrix are not isolated rules. Working through the problems showed how they connect, (AB)T = BT AT and (AB)⁻¹ = B⁻¹A⁻¹ both reverse order for the same underlying reason.