## Concept Summary

ch2.5 checked whether vectors are linearly independent.
ch2.6 goes one step further: can those independent vectors cover the entire space?

**Span and Generating Set**

The set of all linear combinations of $\mathcal{A} = \{x_1, \dots, x_k\}$ is called the span of $\mathcal{A}$.

$$\text{span}[\mathcal{A}] = \left\{ \sum_{i=1}^k \lambda_i x_i \;\middle|\; \lambda_i \in \mathbb{R} \right\}$$

When the span covers all of $V$, $\mathcal{A}$ is called a generating set of $V$. In other words, these vectors alone are enough to cover the entire space.

**Basis**

A generating set can include redundant vectors and still work. A basis removes that redundancy: it is a linearly independent set that still spans the space. Remove any single vector and the space is no longer covered.

Equivalent conditions for $\mathcal{B}$ to be a basis of $V$:
- minimal generating set
- maximal linearly independent set (adding any vector immediately creates linear dependence)
- every vector in $V$ can be expressed as a unique linear combination of $\mathcal{B}$

A basis is not unique, but every basis of the same space has the same number of vectors. That number is the dimension of the space.

**Finding a Basis**

- write the spanning vectors as columns of a matrix $A$
- apply Gaussian elimination to get row-echelon form (ch2.3)
- the original vectors corresponding to pivot columns form a basis

**Rank**

The number of linearly independent columns of $A$ is the rank, written $\text{rk}(A)$. Column rank and row rank are always equal.

$$\text{rk}(A) = \text{rk}(A^\top)$$

Key properties:
- for an $n \times n$ matrix, $\text{rk}(A) = n$ implies invertibility
- $Ax = b$ has a solution if and only if $\text{rk}(A) = \text{rk}(A \mid b)$
- the dimension of the null space equals $n - \text{rk}(A)$, known as the Rank-Nullity theorem
- $\text{rk}(A) = \min(m, n)$ means full rank; anything less is rank deficient


## Verification

**Example 2.16**

A basis is not unique. Three different sets $\mathcal{B}$, $\mathcal{B}_1$, $\mathcal{B}_2$ all span the same $\mathbb{R}^3$. Verified by checking linear independence and confirming that columns of $\mathcal{B}_1$ and $\mathcal{B}_2$ are representable by $\mathcal{B}$.

**Example 2.17**

Given four vectors $x_1, x_2, x_3, x_4$, find the basis of subspace $U$. Applied Gaussian elimination step by step to identify pivot columns and extract the basis vectors.

**Example 2.18 and Rank Properties**

Computed the rank of two matrices from Example 2.18. Used the same matrices to verify the following rank properties:
- $\text{rk}(A) = \text{rk}(A^\top)$
- $n \times n$ matrix with $\text{rk}(A) = n$ is invertible
- null space dimension $= n - \text{rk}(A)$
- full rank / rank deficient identification

In [27]:
# Example 2.16
import numpy as np

# R³ basis examples 
B  = np.array([[1,0,0],[0,1,0],[0,0,1]])      # standard basis
B1 = np.array([[1,1,1],[0,1,1],[0,0,1]])
B2 = np.array([[0.5,1.8,-2.2],[0.8,0.3,-1.3],[0.4,0.3,3.5]])

# verify linear independence
assert np.linalg.matrix_rank(B)  == 3, f"expected 3, got {np.linalg.matrix_rank(B)}"
assert np.linalg.matrix_rank(B1) == 3, f"expected 3, got {np.linalg.matrix_rank(B1)}"
assert np.linalg.matrix_rank(B2) == 3, f"expected 3, got {np.linalg.matrix_rank(B2)}"
print("B  is linearly independent:", np.linalg.matrix_rank(B)  == 3)
print("B1 is linearly independent:", np.linalg.matrix_rank(B1) == 3)
print("B2 is linearly independent:", np.linalg.matrix_rank(B2) == 3)

# verify B1, B2 span the same space as B
print("\nB1 spans the same space as B:")
for i, v in enumerate(B1.T):
    x = np.linalg.solve(B, v)        # Bx = v
    assert np.allclose(B @ x, v), f"B1 col {i+1} not representable by B"
    print(f"  col {i+1}:", "same space" if np.allclose(B @ x, v) else "different space")

print("\nB2 spans the same space as B:")
for i, v in enumerate(B2.T):
    x = np.linalg.solve(B, v)
    assert np.allclose(B @ x, v), f"B2 col {i+1} not representable by B"
    print(f"  col {i+1}:", "same space" if np.allclose(B @ x, v) else "different space")

B  is linearly independent: True
B1 is linearly independent: True
B2 is linearly independent: True

B1 spans the same space as B:
  col 1: same space
  col 2: same space
  col 3: same space

B2 spans the same space as B:
  col 1: same space
  col 2: same space
  col 3: same space


In [ ]:
# Example 2.17

def gaussian_elimination(A):
    A = A.astype(float)
    rows, cols = A.shape
    pivot_cols = []
    row = 0
    for col in range(cols):
        if row >= rows:
            break
        if A[row, col] == 0:
            for r in range(row+1, rows):
                if A[r, col] != 0:
                    A[[row, r]] = A[[r, row]]
                    break
        if A[row, col] == 0:
            continue
        for r in range(row+1, rows):
            A[r] -= (A[r, col] / A[row, col]) * A[row]
        pivot_cols.append(col)
        print(f"step {col+1}:\n", np.round(A, 4), "\n")
        row += 1
    return A, pivot_cols

A = np.array([
    [ 1,  2,  3, -1],
    [ 2, -1, -4,  8],
    [-1,  1,  3, -5],
    [-1,  2,  5, -6],
    [-1, -2, -3,  1]
], dtype=float)

x1, x2, x3, x4 = A[:, 0], A[:, 1], A[:, 2], A[:, 3]

print("original matrix:\n", A, "\n")
_, pivot_cols = gaussian_elimination(A.copy())

print("pivot columns:", [col+1 for col in pivot_cols])
print("basis of U: {x1, x2, x4} =", [f"x{col+1}" for col in pivot_cols])
print("rank:", len(pivot_cols))


original matrix:
 [[ 1.  2.  3. -1.]
 [ 2. -1. -4.  8.]
 [-1.  1.  3. -5.]
 [-1.  2.  5. -6.]
 [-1. -2. -3.  1.]] 

step 1:
 [[  1.   2.   3.  -1.]
 [  0.  -5. -10.  10.]
 [  0.   3.   6.  -6.]
 [  0.   4.   8.  -7.]
 [  0.   0.   0.   0.]] 

step 2:
 [[  1.   2.   3.  -1.]
 [  0.  -5. -10.  10.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   1.]
 [  0.   0.   0.   0.]] 

step 4:
 [[  1.   2.   3.  -1.]
 [  0.  -5. -10.  10.]
 [  0.   0.   0.   1.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]] 

pivot columns: [1, 2, 4]
basis of U: {x1, x2, x4} = ['x1', 'x2', 'x4']
rank: 3


In [ ]:
# Example 2.18 
# same gaussian elimination method as Example 2.17 applied

A1 = np.array([[1, 0, 1],
               [0, 1, 1],
               [0, 0, 0]])

A2 = np.array([[ 1, 2, 1],
               [-2,-3, 1],
               [ 3, 5, 0]])

assert np.linalg.matrix_rank(A1) == 2, f"expected 2, got {np.linalg.matrix_rank(A1)}"
assert np.linalg.matrix_rank(A2) == 2, f"expected 2, got {np.linalg.matrix_rank(A2)}"
print("rank of A1:", np.linalg.matrix_rank(A1))
print("rank of A2:", np.linalg.matrix_rank(A2))

# property 1. rk(A) == rk(A.T)
assert np.linalg.matrix_rank(A1) == np.linalg.matrix_rank(A1.T), "column rank != row rank"
assert np.linalg.matrix_rank(A2) == np.linalg.matrix_rank(A2.T), "column rank != row rank"
print("\nrank of A1.T:", np.linalg.matrix_rank(A1.T))
print("rank of A2.T:", np.linalg.matrix_rank(A2.T))

# property 2. n×n matrix: rk(A) == n -> invertible
I = np.eye(3)
assert np.linalg.matrix_rank(A1) != 3, "A1 should not be invertible"
assert np.linalg.matrix_rank(A2) != 3, "A2 should not be invertible"
assert int(np.linalg.matrix_rank(I)) == 3, "I should be invertible"
print("\nA1 rank:", np.linalg.matrix_rank(A1), "->", "invertible" if np.linalg.matrix_rank(A1) == 3 else "not invertible")
print("A2 rank:", np.linalg.matrix_rank(A2), "->", "invertible" if np.linalg.matrix_rank(A2) == 3 else "not invertible")
print("I  rank:", int(np.linalg.matrix_rank(I)),  "->", "invertible" if np.linalg.matrix_rank(I) == 3 else "not invertible")

# property 3. null space dimension = n - rk(A)
n = A1.shape[1]
assert n - np.linalg.matrix_rank(A1) == 1, f"expected 1, got {n - np.linalg.matrix_rank(A1)}"
assert n - np.linalg.matrix_rank(A2) == 1, f"expected 1, got {n - np.linalg.matrix_rank(A2)}"
print("\nnull space dim of A1:", n - np.linalg.matrix_rank(A1))
print("null space dim of A2:", n - np.linalg.matrix_rank(A2))

# property 4. full rank / rank deficient
assert np.linalg.matrix_rank(A1) < min(A1.shape), "A1 should be rank deficient"
assert np.linalg.matrix_rank(A2) < min(A2.shape), "A2 should be rank deficient"
assert int(np.linalg.matrix_rank(I)) == min(I.shape), "I should be full rank"
print("\nA1:", "full rank" if np.linalg.matrix_rank(A1) == min(A1.shape) else "rank deficient")
print("A2:", "full rank" if np.linalg.matrix_rank(A2) == min(A2.shape) else "rank deficient")
print("I :", "full rank" if np.linalg.matrix_rank(I)  == min(I.shape)  else "rank deficient")

rank of A1: 2
rank of A2: 2

rank of A1.T: 2
rank of A2.T: 2

A1 rank: 2 -> not invertible
A2 rank: 2 -> not invertible
I  rank: 3 -> invertible

null space dim of A1: 1
null space dim of A2: 1

A1: rank deficient
A2: rank deficient
I : full rank


## Reflection Note

The progression from ch2.5 to ch2.6 felt natural. Knowing that vectors are independent is one thing, but basis formalizes what it means for a set of vectors to be just enough to describe an entire space.

Verifying Example 2.16 made the non-uniqueness of basis concrete. Three structurally different sets all passed the same checks, which made it clear that what matters is not the specific vectors but whether they are independent and span the space.

np.linalg.matrix_rank() had been used before without much thought, but understanding that rank counts linearly independent columns made the function feel more grounded. Seeing how it connects to invertibility, null space dimension, and solution existence through the rank properties tied several earlier concepts together.